### PR TITLE
Adding labels to controller buttons

### PR DESCRIPTION
**Pull request by fernandofks**
## Describe your changes

Added labels to the controller buttons

## Checklist before requesting a review

Fill in by placing an x between the brackets below.

- [x] I have performed a self-review of my code
- [x] I have merged the master branch into my branch so it is up to date
- [x] I have verified that the code will build and run
- [x] I have checked that my changes do not conflict with other team members' work
- [x] I have added or edited pages on the wiki to reflect these changes

## Anything else we should know?

N/A

### CODE REVIEW

**Review by imngui — CHANGES_REQUESTED** [review]
I tried building the controller_button branch again and neither the UI nor the buttons show up when I build on for the headset. When I press play in Unity, there UI shows up, so there might be some build settings that are not properly set for VR.

**Comment by fernandofks** [comment]
Did you try UI_controller_button branch from this PR? Or the controller_button only? Can you print screen your building settings?

**Comment by imngui** [comment]
I wasn't aware that there was another branch. In the future just merge changes into the branch you are working on so we don't have an excess of branches. I will try it now though.

**Comment by imngui** [comment]
Okay, I have tested the UI_controller_button branch and nothing has changed. Can you please write up build instructions going over the build settings that must be modified so that anyone trying to compile this will not run into the same issues.

**Comment by fernandofks** [comment]
I didn't understando what you said. Did you pull the UI_controller_button branch from both RADER and VR_Robot? I'm saying this because the building setting should be the same as the main.

**Pull request closed without merging**
