### PR TITLE
Controller button

### PR DESCRIPTION
**Pull request by fernandofks**
## Describe your changes
What is the purpose of this part of the project? Which assets and/or scripts are you adding or editing? Describe below.

This code let's the user activate the UI buttons through the hand controllers.

## Checklist before requesting a review
Fill in by placing an x between the brackets below.
- [x] I have performed a self-review of my code
- [x] I have merged the master branch into my branch so it is up to date
- [x] I have verified that the code will build and run
- [x] I have checked that my changes do not conflict with other team members' work
- [x] I have added or edited pages on the wiki to reflect these changes

## Anything else we should know?
Any issues introduced by these changes or bugs we should be aware of? Describe below or mark "N/A".

N/A

### A grad student will review your changes and either approve and merge them or request changes. Please be responsive if changes are requested. Thanks!

### CODE REVIEW

**Comment by imngui** [comment]
Before we merge, there are a couple of things that need to be fixed. First, the UI is gone, so the user cannot even determine what actions they can perform. Additionally, I am not sure what the buttons do as they have no labels, nor are there any instructions explaining their purpose. Once these are addressed, we can merge.

**Review by imngui — CHANGES_REQUESTED** [review]
Before we merge, there are a couple of things that need to be fixed. First, the UI is gone, so the user cannot even determine what actions they can perform. Additionally, I am not sure what the buttons do as they have no labels, nor are there any instructions explaining their purpose. Once these are addressed, we can merge.

**Comment by fernandofks** [comment]
I'm not sure what do you mean with "the UI is gone". 

I didn't put labels in the button because there are already some labels on them. I will attach a screenshoot here. I can add the label in the UI or try to modify the current labels on the controller so it is easy to understand.
Screenshot 2024-10-31 135009

**Comment by imngui** [comment]
The UI for controlling joint angles, starting and stopping recording, etc which was present before is now gone. It should still be present even though we have buttons to do the job now. Additionally, the buttons do not have labels on them in the main scene. Attached are a couple images that we just took after compiling the controller_buttons branch. 

9a0de4885c5550dc8e647fb80aae1380
6210f92ea5a874eb8d6edb672f7e1645

**Comment by fernandofks** [comment]
I believe I understand now what is happening. There was a bug we were trying to solve last week about the UI not appearing. André could solve it and push to main. But for some reason your code is not updated. Did you do pull? Maybe the labels will appear when you solve this.

**Comment by fernandofks** [comment]
I will close this pull request since I created another one (Adding labels to controller buttons #9)

**Pull request closed without merging**
