### PR TITLE
Controller button to UI

### PR DESCRIPTION
**Pull request by fernandofks**
## Describe your changes

What is the purpose of this part of the project? Which assets and/or scripts are you adding or editing? Describe below.

## Checklist before requesting a review

Fill in by placing an x between the brackets below.

- [X] I have performed a self-review of my code
- [X] I have merged the master branch into my branch so it is up to date
- [X] I have verified that the code will build and run
- [X] I have checked that my changes do not conflict with other team members' work
- [X] I have added or edited pages on the wiki to reflect these changes

## Anything else we should know?

N/A

### CODE REVIEW

**Review by imngui — CHANGES_REQUESTED** [review]
I pulled the code and tried building it but no UI or controller buttons showed up. The main branch still builds the UI, so something in the branch is messing up the UI.

**Comment by fernandofks** [comment]
Hi @imngui , In unity editor, can you click on the SetupUI script and in the public space from pressA, pressB, pressX, pressY, put the respective actions (PressA, PressB, PressX, PressY) by clicking on the circle button on the right side of the empty space and searching them? I created these action in the branch from unity editor. We can make a call if it doesn’t work

**Comment by fernandofks** [comment]
I did some updates, now you can just pull the changes and don't need to worry about the last comment

**Comment by imngui** [comment]
> I did some updates, now you can just pull the changes and don't need to worry about the last comment

I pulled the latest updates. The UI is back and it the mirror button seems like it is working. Good work!

The other two buttons do not seem to work. When I press the A button it outputs:

 _NullReferenceException: Object reference not set to an instance of an object. NullReferenceException while executing 'performed' callbacks of 'XRIRightHand/PressA[/OculusTouchControllerRight/primarybutton]'_

**Comment by fernandofks** [comment]
Hi @imngui , I updated the code with the mirror, replay and record button working. Can you check it please?

**Review by imngui — APPROVED** [review]
Tested and works well.

**Pull request merged**
